# Generated by Django 4.1.1 on 2022-09-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicant_email',
            field=models.EmailField(max_length=254),
        ),
    ]
