# Generated by Django 3.2.9 on 2022-07-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=9999)),
                ('last_name', models.CharField(max_length=9999)),
                ('email', models.EmailField(max_length=999)),
                ('details', models.TextField()),
            ],
        ),
    ]
