# Generated by Django 3.2.9 on 2022-08-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0003_solution_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='solution_category',
            field=models.CharField(choices=[('Network', 'Network'), ('Digital Marketing ', 'Digital Marketing '), ('Data Science & Analytics', 'Data Science & Analytics')], default='Network', max_length=9999),
        ),
    ]
